name        : glibc
version     : 2.23
release     : 30
source     :
    - http://ftp.gnu.org/gnu/glibc/glibc-2.23.tar.xz : 94efeb00e4603c8546209cefb3e1a50a5315c86fa9b078b6fad758e187ce13e9
license     :
    - GPL-3.0
summary     : This package contains the GNU C libraries and header files
description : |
    This package contains the GNU C libraries and header files.  The GNU C library was written originally by Roland McGrath, and is currently maintained by Ulrich Drepper.  Some parts of the library were contributed or worked on by other people. You'll need this package to compile programs.
clang      : no
libsplit   : no
devel      : yes
autodep    : no
emul32     : yes
patterns   :
    - 32bit: /lib/ld-linux.so.2
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
setup      : |
    # Solus integration
    %patch -p1 < $pkgfiles/0001-ldd-Force-correct-RTLDLIST-for-Solus.patch
    # GCC6:
    %patch -p1 < $pkgfiles/0001-stdlib-Add-missing-curly-braves-for-GCC6.patch
    %patch -p1 < $pkgfiles/0002-nis-Fix-use-of-braces-with-GCC6.patch
    # Ref: https://bugs.gentoo.org/show_bug.cgi?id=584916
    # Ref: https://bugs.python.org/issue27287
    %patch -p1 < $pkgfiles/forkpty_python_sigsegv.patch
    # Security
    %patch -p1 < $pkgfiles/security/cve-2016-3075.patch
    %patch -p1 < $pkgfiles/security/cve-2016-4429.patch
    sed -e '/ia32/s/^/1:/' -e '/SSE2/s/^1://' -i  sysdeps/i386/i686/multiarch/mempcpy_chk.S
    mkdir glibc-build
    pushd glibc-build
    
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        mkdir b32
        pushd b32
        export CC="gcc -m32"
        export CXX="g++ -m32"
        export BUILDHOST="i686-pc-linux-gnu"
        export CFLAGS="-O3 -g2 -mtune=generic -march=i686"
    else
        mkdir b64
        pushd b64
        export CC="gcc"
        export CXX="g++"
        export BUILDHOST="x86_64-solus-linux"
        export CFLAGS="-O3 -g2 -mtune=generic -march=x86-64"
    fi
    echo "slibdir=%libdir%" >> configparms
    echo "rtlddir=%libdir%" >> configparms
    # these params need to be coming from ypkg (build=)
    
    export LANGUAGE="C"
    export LC_ALL="C"
    export LANG="C"
    
    ../../configure \
           --enable-add-ons \
           --enable-bind-now \
           --enable-kernel=3.14.32 \
           --without-cvs \
           --without-gd \
           --without-selinux \
           --disable-profile \
           --prefix=/usr \
           --mandir=/usr/share/man \
           --infodir=/usr/share/info \
           --libexecdir=%libdir%/misc \
           --enable-obsolete-rpc \
           --enable-lock-elision=yes \
           --libdir=%libdir% \
           --build=${BUILDHOST} \
           --with-pkgversion='Solus Project'
    popd
    popd
build      : |
    pushd glibc-build
    export LANGUAGE="C"
    export LC_ALL="C"
    export LANG="C"
    
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        pushd b32
        export CC="gcc -m32"
        export CXX="g++ -m32"
        export CFLAGS="-O3 -g2 mtune=generic -march=i686"
    else
        pushd b64
        export CC="gcc"
        export CXX="g++"
        export CFLAGS="-O3 -g2 -mtune=generic -march=x86-64"
    fi
    
    %make
    
    popd
    popd
install    : |
    pushd glibc-build
    
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        pushd b32
        %make_install install_root=$installdir
        # Need this guy for 32-bit too, otherwise Steam blows a gasket
        %make_install install_root=$installdir localedata/install-locales
        
        mkdir $installdir/lib
        # Interestingly enough, /lib == /lib64 on Solus.
        ln -sv /usr/lib32/ld-linux.so.2 $installdir/lib/ld-linux.so.2
    else
        pushd b64
        %make_install install_root=$installdir
        %make_install install_root=$installdir localedata/install-locales
        
        if [[ -f $installdir/etc/ld.so.cache ]]; then
            rm -v $installdir/etc/ld.so.cache
        fi
        
        if [[ -f $installdir/etc/localetime ]]; then
            rm -v $installdir/etc/localtime
        fi
        
        install -d -D -m 00755 $installdir/var/run/nscd
        install -d -D -m 00755 $installdir/var/db/nscd
        
        if [[ -d $installdir/usr/share/zoneinfo ]]; then
            rm -rvf $installdir/usr/share/zoneinfo
        fi
        
        if [[ -f $installdir/usr/sbin/zdump ]]; then
            rm -v $installdir/usr/sbin/zdump
        fi
        
        mkdir $installdir/lib64
        ln -sv /usr/lib64/ld-linux-x86-64.so.2 $installdir/lib64/ld-linux-x86-64.so.2
    fi
    
    
    # libbsd compat link
    ln -sv libbsd-compat.a $installdir/%libdir%/libbsd.a
