name        : glibc
version     : 2.18
release     : 10
source      :
    - http://ftp.gnu.org/gnu/glibc/glibc-2.18.tar.xz : 2cb4e1e381928f1e5e55e71ab1ba8e0ea7ede75ff9709770435bfd018ea257a3
homepage    : http://www.gnu.org/software/libc/
license     :
    - GPL-3.0
summary     : This package contains the GNU C libraries and header files
description : |
    This package contains the GNU C libraries and header files.  The GNU C library was written originally by Roland McGrath, and is currently maintained by Ulrich Drepper.  Some parts of the library were contributed or worked on by other people. You'll need this package to compile programs.
clang      : no
libsplit   : no
devel      : yes
setup      : |
    # ordinary patches..
    %patch -p1 < $pkgfiles/ptrace_add_prefix_to_peeksiginfoargs.patch
    %patch -p1 < $pkgfiles/glibc-2.18-make-4.patch
    
    # security patches
    %patch -p1 < $pkgfiles/security/cve-2013-4237.patch
    %patch -p1 < $pkgfiles/security/cve-2013-4332.patch
    %patch -p1 < $pkgfiles/security/cve-2013-4458.patch
    %patch -p1 < $pkgfiles/security/cve-2014-0475.patch
    %patch -p1 < $pkgfiles/security/cve-2014-6040.patch
    
    mkdir glibc-build
    pushd glibc-build
    
    echo "slibdir=%libdir%" >> configparms
    echo "rtlddir=%libdir%" >> configparms
    # these params need to be coming from ypkg (build=)
    
    export CFLAGS="-O3 -g -U_FORTIFY_SOURCE -fno-strict-aliasing -fomit-frame-pointer -mno-tls-direct-seg-refs -mtune=generic -march=x86-64"
    export LANGUAGE="C"
    export LC_ALL="C"
    export LANG="C"
    export CC="gcc"
    export CXX="g++"
    
    ../configure \
           --with-tls \
           --with-__thread \
           --enable-add-ons=nptl,libidn \
           --enable-bind-now \
           --enable-kernel=2.6.25 \
           --enable-stackguard-randomization \
           --without-cvs \
           --without-gd \
           --without-selinux \
           --disable-profile \
           --prefix=/usr \
           --mandir=/usr/share/man \
           --infodir=/usr/share/info \
           --libexecdir=%libdir%/misc \
           --enable-obsolete-rpc \
           --libdir=%libdir% \
           --build=x86_64-evolveos-linux
           
    
    popd
build      : |
    pushd glibc-build
    export CFLAGS="-O3 -g -U_FORTIFY_SOURCE -fno-strict-aliasing -fomit-frame-pointer -mno-tls-direct-seg-refs -mtune=generic -march=x86-64"
    export LANGUAGE="C"
    export LC_ALL="C"
    export LANG="C"
    export CC="gcc"
    export CXX="g++"
    
    %make
    
    popd
install    : |
    pushd glibc-build
    %make_install install_root=$installdir
    %make_install install_root=$installdir localedata/install-locales
    
    # libbsd compat link
    ln -sv libbsd-compat.a $installdir/%libdir%/libbsd.a
    
    if [[ -f $installdir/etc/ld.so.cache ]]; then
        rm -v $installdir/etc/ld.so.cache
    fi
    
    if [[ -f $installdir/etc/localetime ]]; then
        rm -v $installdir/etc/localtime
    fi
    
    install -d -D -m 00755 $installdir/var/run/nscd
    install -d -D -m 00755 $installdir/var/db/nscd
    
    if [[ -d $installdir/usr/share/zoneinfo ]]; then
        rm -rvf $installdir/usr/share/zoneinfo
    fi
    
    if [[ -f $installdir/usr/sbin/zdump ]]; then
        rm -v $installdir/usr/sbin/zdump
    fi
    
    popd
    
    mkdir $installdir/lib64
    ln -sv /usr/lib64/ld-linux-x86-64.so.2 $installdir/lib64/ld-linux-x86-64.so.2
