name        : glibc
version     : 2.22
release     : 15
source     :
    - http://ftp.gnu.org/gnu/glibc/glibc-2.22.tar.xz : eb731406903befef1d8f878a46be75ef862b9056ab0cde1626d08a7a05328948
license     :
    - GPL-3.0
summary     : This package contains the GNU C libraries and header files
description : |
    This package contains the GNU C libraries and header files.  The GNU C library was written originally by Roland McGrath, and is currently maintained by Ulrich Drepper.  Some parts of the library were contributed or worked on by other people. You'll need this package to compile programs.
clang      : no
libsplit   : no
devel      : yes
autodep    : no
setup      : |  
    mkdir glibc-build
    pushd glibc-build
    
    echo "slibdir=%libdir%" >> configparms
    echo "rtlddir=%libdir%" >> configparms
    # these params need to be coming from ypkg (build=)
    
    export CFLAGS="-O3 -g -U_FORTIFY_SOURCE -fno-strict-aliasing -fomit-frame-pointer -mno-tls-direct-seg-refs -mtune=generic -march=x86-64"
    export LANGUAGE="C"
    export LC_ALL="C"
    export LANG="C"
    export CC="gcc"
    export CXX="g++"
    
    ../configure \
           --with-tls \
           --with-__thread \
           --enable-add-ons \
           --enable-bind-now \
           --enable-kernel=2.6.25 \
           --enable-stackguard-randomization \
           --without-cvs \
           --without-gd \
           --without-selinux \
           --disable-profile \
           --prefix=/usr \
           --mandir=/usr/share/man \
           --infodir=/usr/share/info \
           --libexecdir=%libdir%/misc \
           --enable-obsolete-rpc \
           --libdir=%libdir% \
           --build=x86_64-solus-linux
           
    
    popd
build      : |
    pushd glibc-build
    export CFLAGS="-O3 -g -U_FORTIFY_SOURCE -fno-strict-aliasing -fomit-frame-pointer -mno-tls-direct-seg-refs -mtune=generic -march=x86-64"
    export LANGUAGE="C"
    export LC_ALL="C"
    export LANG="C"
    export CC="gcc"
    export CXX="g++"
    
    %make
    
    popd
install    : |
    pushd glibc-build
    %make_install install_root=$installdir
    %make_install install_root=$installdir localedata/install-locales
    
    # libbsd compat link
    ln -sv libbsd-compat.a $installdir/%libdir%/libbsd.a
    
    if [[ -f $installdir/etc/ld.so.cache ]]; then
        rm -v $installdir/etc/ld.so.cache
    fi
    
    if [[ -f $installdir/etc/localetime ]]; then
        rm -v $installdir/etc/localtime
    fi
    
    install -d -D -m 00755 $installdir/var/run/nscd
    install -d -D -m 00755 $installdir/var/db/nscd
    
    if [[ -d $installdir/usr/share/zoneinfo ]]; then
        rm -rvf $installdir/usr/share/zoneinfo
    fi
    
    if [[ -f $installdir/usr/sbin/zdump ]]; then
        rm -v $installdir/usr/sbin/zdump
    fi
    
    popd
    
    mkdir $installdir/lib64
    ln -sv /usr/lib64/ld-linux-x86-64.so.2 $installdir/lib64/ld-linux-x86-64.so.2
